pipeline {
    agent { node { label 'linux && jdk11' } }

    pipeline {
        agent any

        stages {
            stage('STAGE 00'){
                steps{
                    echo "Pipeline Usando Jenkinsfile"
                }
            }

            stage('STAGE 01'){
                steps{
                    echo "Pipeline Usando Jenkinsfile"
                }
            }
        }
    }
}
