pipeline { 
    agent none

    stages { 
        stage('STAGE 00'){ 
            steps{
                echo "Pipeline Usando Jenkinsfile"
            }
        }

        stage('STAGE 01'){ 
            steps{
                echo "Pipeline Usando Jenkinsfile"
            }
        }
        stage('Unit Test') {
                    steps {
                        println('Skip unit test')
                        sh 'bash -x devops-tools/pipeline-shared-librares/unit-tests.sh'
                    }
                }
    } 
} 