language: java
jdk:
  - oraclejdk8
#script:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


before_deploy:
  - git config --local user.name "DiegoDannielDev"
  - git config --local user.email "diego.diniz.dev@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: heroku
  api_key: fe3d2003-8c3f-4dad-a45d-b8deac470ec2
  app: contatogestao



